services:

  spoof-dpi:
    container_name: "spoof-dpi"
    image: "spoof-dpi:latest"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: spoof-dpi
    hostname: spoof-dpi
    ports:
      - "${PORT}:${PORT}"
    dns:
      # OpenDNS
      - 208.67.222.222
      - 208.67.220.220
    networks:
      - dpi

networks:
  dpi:
    name: dpi
    driver: bridge
