# Trigger this workflow on release
on:
  release:
    types: [created]

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    - name: Display Go version
      run: go version

    - name: Build and publish linux/amd64
      env: 
        GOOS: darwin
        GOARCH: amd64
      run: |
        go build -ldflags="-w -s" github.com/xvzc/SpoofDPI/cmd/spoof-dpi 
        tar -zcvf "spoof-dpi-$GOOS-$GOARCH.tar.gz" ./spoof-dpi && rm -rf ./spoof-dpi
        gh release upload ${{github.event.release.tag_name}} "spoof-dpi-$GOOS-$GOARCH.tar.gz"
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash
